package gameplay;

public enum Message {
    ITEM_ADDED,
    ITEM_TOO_BIG,
    ITEM_TOO_HEAVY,
    ITEM_REMOVED,
    ITEM_NOT_FOUND,
    ITEM_USED,
    ITEM_DESTROYED,
    INVENTORY_CLEARED,
    INVENTORY_EMPTY,
    WEAPON_TAKEN,
    WEAPON_PUT_AWAY,
    IS_NOT_WEAPON,
    ARMOR_TAKEN,
    IS_NOT_ARMOR,
    ARMOR_PUT_AWAY,
    DAMAGE_GAINED,
    PLAYER_DEAD,
}
